version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: receipt-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: receipt_integration
      MYSQL_USER: receipt_user
      MYSQL_PASSWORD: receipt_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema:/docker-entrypoint-initdb.d
    networks:
      - receipt-network

  redis:
    image: redis:7-alpine
    container_name: receipt-redis
    ports:
      - "6379:6379"
    networks:
      - receipt-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: receipt-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/receipt_integration
      SPRING_DATASOURCE_USERNAME: receipt_user
      SPRING_DATASOURCE_PASSWORD: receipt_password
      SPRING_REDIS_HOST: redis
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - receipt-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: receipt-frontend
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8080/api
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - receipt-network

networks:
  receipt-network:
    driver: bridge

volumes:
  mysql_data: